name: camping_app
description: "A camping companion app with weather, AI assistant, maps, checklist, and more."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Core State & Local Database
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location, Maps, and Navigation
  geolocator: ^14.0.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  compassx: ^1.0.1
  path_provider: ^2.1.6

  # UI Design, Networking & Environment
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  flutter_gemma: ^0.13.6
  flutter_compass: ^0.8.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.2
  internet_connection_checker_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
